### ISSUE TITLE
[BUG] CSE not redirecting to top of URL

### ISSUE THREAD

**Issue by DavidSchechter** [Cizzuk/CSE#11] opened 2024-09-07 15:06 UTC
Root cause:
Top of url included support url. No redirects happen .

Sets to reproduce:

- Set top of url to - https://google.com/search?udm=14&q= (this is a redirect to the new “web” tab in google search).
- Set default search engine as - Google - both in CSE and Safari Settings
- Attempt to make a search

Issue is reproducible if DuckDuckGo is set as the default search engine both in CSE and Safari Settings.

Thank you in advance

**Comment by Cizzuk** [comment] 2024-09-07 15:34
Hello.
This bug is caused by your Top of URL being "google.com".
Google's domain is with WWW, so if you change the domain to "www.google.com", this bug will not occur.

It will be fixed in v2.7, which will be available after the release of iOS 18 (probably on September 9).

Thanks for reporting this bug!

**Closed by Cizzuk** 2024-09-07 15:34 UTC
Labels: bug, extension

**Comment by DavidSchechter** [comment] 2024-09-07 15:42
Thank you for your quick response.

Changing to - www.google.com - does resolve the issue.

Thanks again
